apiVersion: apps/v1
kind: Deployment
metadata:
  name: uoslife-sso-api
  namespace: uoslife-sso
  labels:
    app: uoslife-sso-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uoslife-sso-api
  template:
    metadata:
      labels:
        app: uoslife-sso-api
    spec:
      containers:
        - name: uoslife-sso-api
          image: harbor.uoslife.com/uoslife-sso/api:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: production
            - name: APP_URL
              value: https://sso-api.uoslife.team
            - name: APP_PORT
              value: 3000
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: uoslife-sso-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: uoslife-sso-secret
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: uoslife-sso-secret
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: uoslife-sso-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uoslife-sso-secret
                  key: DB_PASSWORD
          imagePullPolicy: Always
      imagePullSecrets:
        - name: harbor.uoslife.com
---
apiVersion: v1
kind: Service
metadata:
  name: uoslife-sso-api
  namespace: uoslife-sso
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
      app: uoslife-sso-api
