apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-sso
  namespace: uoslife
  labels:
    app: uoslife-sso
spec:
  replicas: 5
  selector:
    matchLabels:
      app: server-sso
  template:
    metadata:
      labels:
        app: server-sso
    spec:
      containers:
        - name: server-sso
          image: 755333364809.dkr.ecr.ap-northeast-2.amazonaws.com/uoslife-sso:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: production
            - name: APP_URL
              value: https://sso-api.uoslife.team
            - name: SERVICE_URL
              value: https://sso.uoslife.team
            - name: ADMIN_URL
              value: https://sso-admin.uoslife.team
            - name: APP_PORT
              value: "3000"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: DB_PASSWORD
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: APP_SECRET
            - name: APP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: APP_ENCRYPTION_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: JWT_SECRET_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: AWS_SECRET_ACCESS_KEY
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server-sso
  namespace: uoslife
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: server-sso
