name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Version Code
        id: version
        run: echo "::set-output name=code::$(date +'%Y%m%d%H%M%S')"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor Registry
        uses: docker/login-action@v2
        with:
          registry: harbor.uoslife.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          target: production
          push: true
          platforms:
            linux/amd64
          tags: harbor.uoslife.com/uoslife-sso/api:latest, harbor.uoslife.com/uoslife-sso/api:${{ steps.version.outputs.code }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment uoslife-sso-api uoslife-sso-api=harbor.uoslife.com/uoslife-sso/api:${{ steps.version.outputs.code }}

      - name: Verify Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deployment uoslife-sso-api
