name: Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Version Code
        id: version
        run: echo "::set-output name=code::$(date +'%Y%m%d%H%M%S')"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Image to ECR
        uses: docker/build-push-action@v3
        with:
          context: .
          target: production
          push: true
          platforms:
            linux/amd64
          tags: 747487074043.dkr.ecr.ap-northeast-2.amazonaws.com/uoslife-sso:${{ steps.version.outputs.code }}, 747487074043.dkr.ecr.ap-northeast-2.amazonaws.com/uoslife-sso:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EKS
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment server-sso server-sso=747487074043.dkr.ecr.ap-northeast-2.amazonaws.com/uoslife-sso:${{ steps.version.outputs.code }} -n uoslife

      - name: Verify EKS Deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deployment server-sso -n uoslife
